#!/usr/bin/env python3
"""
Example: Decode PSK signal from WAV file

This example shows how to use the PSK decoder to decode PSK signals
from WAV files (either generated by pydigi or fldigi).

Usage:
    python decode_psk_wav.py <wav_file> <baud> [frequency]

Examples:
    python decode_psk_wav.py test.wav 31.25
    python decode_psk_wav.py psk125.wav 125 1000
"""

import sys
import os
import numpy as np
import wave

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from pydigi.modems.psk_decoder import PSKDecoder


def load_wav(filename):
    """Load WAV file and return samples and sample rate.

    Args:
        filename: Path to WAV file

    Returns:
        Tuple of (samples, sample_rate)
    """
    with wave.open(filename, 'rb') as wf:
        # Get WAV parameters
        n_channels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        framerate = wf.getframerate()
        n_frames = wf.getnframes()

        print(f"WAV file info:")
        print(f"  Channels: {n_channels}")
        print(f"  Sample width: {sampwidth} bytes")
        print(f"  Sample rate: {framerate} Hz")
        print(f"  Duration: {n_frames/framerate:.2f} seconds")

        # Read audio data
        audio_bytes = wf.readframes(n_frames)

        # Convert to numpy array
        if sampwidth == 1:
            # 8-bit unsigned
            samples = np.frombuffer(audio_bytes, dtype=np.uint8)
            samples = (samples.astype(np.float32) - 128) / 128.0
        elif sampwidth == 2:
            # 16-bit signed
            samples = np.frombuffer(audio_bytes, dtype=np.int16)
            samples = samples.astype(np.float32) / 32768.0
        elif sampwidth == 4:
            # 32-bit float
            samples = np.frombuffer(audio_bytes, dtype=np.float32)
        else:
            raise ValueError(f"Unsupported sample width: {sampwidth}")

        # Convert stereo to mono if needed
        if n_channels == 2:
            samples = samples.reshape(-1, 2).mean(axis=1)
            print(f"  Converted stereo to mono")

        return samples, framerate


def decode_psk_wav(wav_file, baud, frequency=1000, afc=True, squelch=False):
    """Decode PSK signal from WAV file.

    Args:
        wav_file: Path to WAV file
        baud: PSK baud rate (31.25, 62.5, 125, 250, 500)
        frequency: Carrier frequency in Hz (default: 1000)
        afc: Enable automatic frequency correction (default: True)
        squelch: Enable squelch (default: False)
    """
    print(f"\n{'='*70}")
    print(f"Decoding PSK{int(baud)} from: {wav_file}")
    print(f"{'='*70}\n")

    # Load WAV file
    samples, sample_rate = load_wav(wav_file)
    print()

    # Initialize decoder
    print(f"Initializing PSK{int(baud)} decoder...")
    print(f"  Baud rate: {baud}")
    print(f"  Frequency: {frequency} Hz")
    print(f"  AFC: {afc}")
    print(f"  Squelch: {squelch}")
    print()

    decoder = PSKDecoder(
        baud=baud,
        sample_rate=sample_rate,
        frequency=frequency,
        afc_enabled=afc,
        squelch_enabled=squelch,
    )

    # Set up text callback
    def text_callback(char):
        print(char, end='', flush=True)

    decoder.set_text_callback(text_callback)

    # Decode
    print("Decoded text:")
    print("-" * 70)
    decoder.process(samples)
    print()
    print("-" * 70)

    # Show statistics
    stats = decoder.get_stats()
    print(f"\nStatistics:")
    print(f"  Symbols received: {stats['symbols_received']}")
    print(f"  Characters decoded: {stats['chars_decoded']}")
    print(f"  Final metric: {stats['metric']:.2f}")
    print(f"  Final DCD: {stats['dcd']}")
    print(f"  Final frequency: {stats['frequency']:.2f} Hz")
    print(f"  Frequency error: {stats['freqerr']:.4f} Hz")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    wav_file = sys.argv[1]
    baud = float(sys.argv[2])
    frequency = float(sys.argv[3]) if len(sys.argv) > 3 else 1000.0

    if not os.path.exists(wav_file):
        print(f"Error: File not found: {wav_file}")
        sys.exit(1)

    decode_psk_wav(wav_file, baud, frequency)
